jobs:
  check_package_version:
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    name: Check Package Version
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - uses: dudo/tag_check@v1.0.0
        with:
          git_tag_prefix: v

    runs-on: ubuntu-latest

name: Pull Request (main)

on:
  pull_request:
    branches:
      - main
