name: Deploy gh-pages

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Deploy
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout main
        uses: actions/checkout@v2
        with:
          ref: main
      - name: Install Node.JS
        uses: actions/setup-node@v1
        with:
          node-version: "12.19.0"
      - name: Install Yarn
        run: npm install --global yarn@1.22.10
      - name: Setup CI
        run: yarn ci
      - name: Build
        run: yarn build
      - name: Deploy
        run: yarn deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
