name: Release Portfolio

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release Portfolio
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout 'main' Branch
        uses: actions/checkout@v2
        with:
          ref: main
      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/fermium'
      - name: Remove 'node_modules'
        run: rm -rf node_modules
      - name: Install Yarn
        run: npm install --global yarn
      - name: Configure CI
        run: yarn install --frozen-lockfile
      - name: Build
        run: yarn build
      - name: Publish
        run: yarn publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
